name: Gateway Sharness

on:
  workflow_dispatch:
  pull_request:
    paths: ['gateway/**']
  push:
    branches: ['main']
    paths: ['gateway/**']

jobs:
  sharness:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: Checkout Kubo
        uses: actions/checkout@v3
        with:
          repository: ipfs/kubo
          path: kubo
      - name: Install Missing Tools
        run: sudo apt install -y socat net-tools fish libxml2-utils
      - name: Restore Go Cache
        uses: protocol/cache-go-action@v1
        with:
          name: ${{ github.job }}
      - name: Install sharness dependencies
        run: make test_sharness_deps
        working-directory: kubo
      - name: Run Sharness Tests
        run: find . -maxdepth 1 -name "*gateway*" -exec {} \;
        working-directory: kubo/test/sharness
